### DISCUSSION TITLE
docker-entrypoint-initdb.d crashes container

### DISCUSSION THREAD

**Discussion by hsscatlas** [timeplus-io/proton#935] [Q&A] [answered]
Hi Proton/Timeplus team,

I'm trying to have a full mock-up streaming pipeline in a docker-compose file.
In all the examples available in the repository, when deploying the pipeline, the SQL commands are always deployed with something along the lines: 

```
You can use docker exec -it <name> proton-client to run the SQL client in Proton container. Or use the Docker Desktop UI to choose the container, choose "Exec" tab and type proton-client to start the SQL client.

Run the following commands: ...
```
https://github.com/timeplus-io/proton/tree/develop/examples/ecommerce#run-sql

When I mount an init.sql script onto `/docker-entrypoint-initdb.d`, the initialization fails. When I inspect the `entrypoint.sh`, I see that this block is responsible for triggering the error:
```
if [ -n "$(ls /docker-entrypoint-initdb.d/)" ] || [ -n "$PROTON_DB" ]; then
    # port is needed to check if proton-server is ready for connections
    HTTP_PORT=8123

    # Listen only on localhost until the initialization is done
    $gosu /usr/bin/proton-server --config-file="$PROTON_CONFIG" -- --listen_host=127.0.0.1 &
    pid="$!"

    # check if proton is ready to accept connections
    # will try to send ping proton via http_port (max 12 retries by default, with 1 sec timeout and 1 sec delay between retries)
    tries=${PROTON_INIT_TIMEOUT:-12}
    while ! wget --spider -T 1 -q "http://127.0.0.1:$HTTP_PORT/timeplusd/ping" 2>/dev/null; do
        if [ "$tries" -le "0" ]; then
            echo >&2 'Proton init process failed.'
            exit 1
        fi
        tries=$(( tries-1 ))
        sleep 1
    done
```
I don't get why the HTTP_PORT is pinned to 8123, which is ClickHouse's native HTTP port. I would expect it to be 3218 (the Proton's native HTTP port).

What am I missing?

Another question that I have is: once this problem is solved, imagine my pipeline is running. What if I want to deploy a migration/evolution? How to do this by altering only the MV that is being migrated? How to do it properly and without having to interact manually with the proton-client executable within the container? I'm sorry if for this question my knowledge and understanding of the tool is a little bit shallow...

For info, here it is my docker-compose.yaml:

````
services:

  kafka:
    image: bitnami/kafka:3.7.0 # With Kafka 4.0, support for the old record formats v0 and v1 was removed (KIP‑724), and Proton(librdkafka) is not compatible with v2
    hostname: kafka
    ports:
      - "9092:9092"
      - "9997:9997"  # JMX port
      - "9999:9999"  # RMI registry port
      - "29092:29092"  # Additional port for internal comms
    env_file:
      - ../.env
      - .env
    environment:
      # KRaft mode configuration
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "controller,broker"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      # Listeners configuration
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:29092,CONTROLLER://:29093,PLAINTEXT_HOST://:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # JMX configuration
      KAFKA_JMX: "yes"
      KAFKA_JMX_PORT: "9997"
      KAFKA_JMX_HOSTNAME: "kafka"
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.rmi.port=9997 -Djava.rmi.server.hostname=kafka"
      # Cluster communication configuration
      KAFKA_CFG_CONTROLLER_ADVERTISED_LISTENERS: "CONTROLLER://kafka:29093"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CFG_NUM_PARTITIONS: "1"
      KAFKA_CFG_DEFAULT_REPLICATION_FACTOR: "1"
      # Ensuring compatibility with Proton
      KAFKA_CFG_INTER_BROKER_PROTOCOL_VERSION: "3.7.0"
      KAFKA_CFG_LOG_MESSAGE_FORMAT_VERSION: "3.7.0"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - 9080:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_JMXPORT: 9997
      KAFKA_CLUSTERS_0_JMXHOST: kafka
      KAFKA_CLUSTERS_0_JMX_SSL: "false"
      DYNAMIC_CONFIG_ENABLED: "true"

  init-infra-discovery:
    build:
      dockerfile: ./config/Dockerfile
      context: .
    container_name: init-infra-discovery
    env_file:
      - ../.env
      - .env

  xmlgen:
    container_name: xmlgen
    build:
      dockerfile: ./xmlgen/Dockerfile
      context: .
    env_file:
      - ../.env
      - .env

  xml2json:
    container_name: xml2json
    build:
      dockerfile: ./xml2json/Dockerfile
      context: .
    env_file:
      - ../.env
      - .env

  proton:
    image: ghcr.io/timeplus-io/proton:latest
    container_name: proton
    ports:
      - 3218:3218 # HTTP Streaming
      - 8463:8463 # TCP Streaming
    env_file:
      - ../.env
      - .env
    environment:
      PROTON_CLICKHOUSE_SERVER: "${CLICKHOUSE_DB_HOST}:${CLICKHOUSE_DB_PORT_2}"
      PROTON_CLICKHOUSE_USER: "${CLICKHOUSE_DB_USER}"
      PROTON_CLICKHOUSE_PASSWORD: "${CLICKHOUSE_DB_PWD}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:3218/proton/ping"]
      interval: 5s
      timeout: 15s
      retries: 3
      start_period: 15s
    volumes:
      - ./proton/init_sql:/docker-entrypoint-initdb.d # ----> this crashes the container
      # - ./proton/log:/var/log/proton-server
```

**Comment by jovezhong** [comment]
Hi @hugo-catlas , thanks for trying Timeplus.

With the recent code change, the init.sql may not work. One solution is to check the health of proton in the docker compose then run a set of sql via the other container.

To run DDL, both HTTP ports (8123 and 3218 work). The difference is 3218 turns on streaming query by default, so `select count() from kafka_stream` will keep pushing new results to the client.

To change stream/mv, you can use the `proton client` CLI, or use JDBC/Python client. Some of our users also prefer flyway to manage the schema and migration https://docs.timeplus.com/flyway

Let me know whether you are blocked

**Reply by hsscatlas** [reply]
Thank you, @jovezhong for your prompt answer.

Indeed, it was possible to have a side-container for the initialization.
It would be easier though to have the possibility to declare a path of a pipeline/initialization script as an environment variable in the docker container. Doing so would also make it easier to deploy on k8s. The manifest files could then be easily changed in a CI/CD setup.

Last point: I had some trouble setting up time series on grafana using the timeplus/proton plugin. The same visualization works perfectly fine with the ClickHouse plugin, but on Proton it is impossible to have time series for multiple identifiers (say id, timestamp, max_temperature, for instance).

Would it be possible to have the possibility to install the plugin directly from within Grafana instead of having to manually download it? I see that there is an old version available on Grafana's plugin page, though.

Cheers,

Hugo

**Reply by jovezhong** [reply]
Hi @hugo-catlas , I am about to look into the issues you mentioned.  Do you mind creating new discussion topics for grafana integration or other topics? Let's leave this page for the initdb issue. Alternatively you may join our community slack https://timeplus.com/slack we can use thread or huddle/screenshot to discuss multiple topics

**Reply by jovezhong** [reply, marked as answer]
Hi @hugo-catlas , I pushed a new change to the repo to fix the init.d example in the coinbase folder. Please check https://github.com/timeplus-io/proton/commit/9eb028721a324c5f7161574ca48395eab915e2fd

You may follow this example to run DDL when the Timeplus Proton is ready.
Make sure you remove the mount for 
```yaml
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
 ```
Then you can create another container using proton image to use the `proton client --queries-file init.sql`
```yaml
  init_timeplus_resources:
    entrypoint:
      - proton
      - client
      - -h
      - proton
      - --queries-file
      - /script/init.sql
    image: d.timeplus.com/timeplus-io/proton:latest
    volumes:
      - ./initdb.d:/script
    depends_on:
      proton:
        condition: service_healthy
```
Finally if there are other containers need to work with the data stream, you can add depends_on
```yaml
    depends_on:
      proton:
        condition: service_healthy
      init_timeplus_resources:
        condition: service_completed_successfully
```

Let me know whether this works for you. I will check rest of the examples in Proton repo to avoid using init.d. We removed this mainly to better support cluster(multi-node)

**Reply by jovezhong** [reply]
For the grafana plugin, you can check my latest commit https://github.com/timeplus-io/proton/commit/6f8d6c570abf143a9d12325272293d175d522a50

Essentially you can add this in the Docker Compose file
```yaml
  grafana:
    image: grafana/grafana:latest
    pull_policy: always
    ports:
      - 3000:3000
    environment:
      GF_PLUGINS_PREINSTALL: timeplus-proton-datasource@@https://d.timeplus.com/grafana/timeplus-proton-datasource-2.1.2.zip
```

If you need more support, please create a new discussion topic
