### ISSUE TITLE
Cannot use external stream to read data on confluentinc/cp-kafka:7.4.0

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#158]
**Describe what's wrong**

I used the following docker compose file to setup a kafka broker but failed to get any data with the external stream
```sql
CREATE EXTERNAL STREAM transactions_s(raw string) SETTINGS type='kafka', brokers='broker:9092', topic='transactions';
select * from transactions_s;
select * from transactions_s settings seek_to='earliest';
```

**How to reproduce**
The docker compose file (from community)
```yml
---
version: '3.7'
services:
  broker:
    image: confluentinc/cp-kafka:7.4.0
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Replace CLUSTER_ID with a unique base64 UUID using "bin/kafka-storage.sh random-uuid" 
      # See https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-storage-sh
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.4.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  proton:
     image: ghcr.io/timeplus-io/proton:latest
     depends_on:
     - schema-registry

```
Python data generator
pip install kafi
```python
import random
import json

import datetime
import time
from kafi.kafi import Cluster

c = Cluster("local")
p = c.producer("transactions")
id = 0
random.seed(42)
while True:
    row = json.dumps({
        'id': id,
        'from_account': random.randint(0,9),
        'to_account': random.randint(0,9),
        'amount': 1,
        'ts': datetime.datetime.now().isoformat(sep=" ", timespec="milliseconds")
    })
    print(row)
    p.produce(row, key=str(id))
    if id % 1000 == 0:
      p.flush()
    id += 1
    time.sleep(0.01)
    #
    p.close()

```
also need a file in `configs/clusters/local.yaml`
```yaml
kafka:
  bootstrap.servers: localhost:9092
```
**Error message and/or stacktrace**

**Additional context**
