### ISSUE TITLE
Using JSONEachRow as data_format to write JSON to Kafka topic leads to jsonl and invalid JSON

### ISSUE THREAD

**Issue by jovezhong** [timeplus-io/proton#274]
**Describe what's wrong**

Reported by community user

> when creating an external kafka stream with data_format = 'JSONEachRow'  if there are a lot of events per second then each kafka message ends up containing multiple JSON documents which makes it no longer valid JSON kafka messages. Is there a way to force it so that each kafka message only ever contains one event? 

**How to reproduce**
Based on docker compose and SQL on https://github.com/timeplus-io/proton/tree/develop/examples/ecommerce
but add more volume

```yaml
  owl-shop:
    image: quay.io/cloudhut/owl-shop:latest
    #platform: 'linux/amd64'
    environment:
      - SHOP_KAFKA_BROKERS=redpanda:9092
      - SHOP_KAFKA_TOPICREPLICATIONFACTOR=1
      - SHOP_TRAFFIC_INTERVAL_RATE=10
      - SHOP_TRAFFIC_INTERVAL_DURATION=0.01s
    depends_on:
      - redpanda
   ```

**Error message and/or stacktrace**

**Additional context**
