### ISSUE TITLE
Host resolution failure, but i can create external stream  and begin query successfully

### ISSUE THREAD

**Issue by lizhou1111** [timeplus-io/proton#310]
It should throw exception when proton-server cant't resolve the host.
Here are the steps to reproduce the problem
I use docker-compose to start Kafka.
```yaml
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: "2"

services:
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    # volumes:
    #   - ./server.properties:/etc/kafka/server.properties
    #   - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER: PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN
      - KAFKA_SECURITY_INTER_BROKER_PROTOCOL=SASL_PLAINTEXT
      - KAFKA_SASL_ENABLED_MECHANISMS=PLAIN
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      
```
then i create topic `kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic my_topic`

After this, I created external  stream and begin query.
```sql
drop stream if exists test_external1;
create external stream if not exists test_external1(raw string) settings type = 'kafka', brokers = '127.0.0.1:9092', topic = 'my_topic';
select * from test_external1;
```
There is no error message during the process.As a user，everything seems to be fine, I create external stream and run query successfully.But you can't read any data from proton.
In proton-serverv log, it indicates proton cant't resolve the host
```
%3|1700533922.688|FAIL|rdkafka#consumer-5| [thrd:GroupCoordinator]: GroupCoordinator: 85689ba8ab4a:9092: Failed to resolve '85689ba8ab4a:9092': No address associated with hostname (after 144ms in state CONNECT, 4 identical error(s) suppressed)
2023.11.21 10:32:02.688467 [ 53697 ] {} <Warning> KafkaWALSimpleConsumer: Error occurred, error=Local: Host resolution failure, reason=GroupCoordinator: 85689ba8ab4a:9092: Failed to resolve '85689ba8ab4a:9092': No address associated with hostname (after 144ms in state CONNECT, 4 identical error(s) suppressed)
%3|1700533927.051|FAIL|rdkafka#consumer-2| [thrd:GroupCoordinator]: GroupCoordinator: 85689ba8ab4a:9092: Failed to resolve '85689ba8ab4a:9092': No address associated with hostname (after 145ms in state CONNECT, 4 identical error(s) suppressed)
2023.11.21 10:32:07.051885 [ 53696 ] {} <Warning> KafkaWALSimpleConsumer: Error occurred, error=Local: Host resolution failure, reason=GroupCoordinator: 85689ba8ab4a:9092: Failed to resolve '85689ba8ab4a:9092': No address associated with hostname (after 145ms in state CONNECT, 4 identical error(s) suppressed)
%3|1700533927.221|FAIL|rdkafka#consumer-3| [thrd:GroupCoordinator]: GroupCoordinator: 85689ba8ab4a:9092: Failed to resolve '85689ba8ab4a:9092': No address associated with hostname (after 288ms in state CONNECT, 4 identical error(s) suppressed)
2023.11.21 10:32:07.221261 [ 54170 ] {} <Warning> KafkaWALSimpleConsumer: Error occurred, error=Local: Host resolution failure, reason=GroupCoordinator: 85689ba8ab4a:9092: Failed to resolve '85689ba8ab4a:9092': No address associated with hostname (after 288ms in state CONNE
```
