### ISSUE TITLE
CI: do some detailed input check in manual trigger build/manual trigger test

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/proton#442]
**Describe what enhancement you'd like to have**

https://github.com/timeplus-io/proton/blob/develop/.github/workflows/manual_trigger_build.yml#L26
consider if the below input **docker image tag** input illegal, we shall directly exit instead of continue.
![image](https://github.com/timeplus-io/proton/assets/113408135/8baa4b0b-8b9b-406a-b535-482ca0c96ec5)

how to continue this issue?
in the prepare_release prepare_sanitizer stage, we can do a check
```
jobs:
  prepare_sanitizer:
    runs-on: ubuntu-latest
    if: github.event.inputs.build_image_tag == illegal we skip the process.
```
