### ISSUE TITLE
Trigger action workflow when PR is not draft.

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/proton#68]
**Use case**
```
name: Action Name

on:
  pull_request:
    branches: [my_branch]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review --> expected add this event type.
```

**Additional context**
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
https://github.com/reviewdog/action-eslint/issues/29#issuecomment-985939887
