### ISSUE TITLE
When setting PROTON_USER and PROTON_PASSWORD env variables, config merge causes proton to crash

### ISSUE THREAD

**Issue by sarwarbhuiyan** [timeplus-io/proton#927]
compose file

```
version: '3.3'
services:
  proton:
    image: [d.timeplus.com/timeplus-io/proton:latest](http://d.timeplus.com/timeplus-io/proton:latest)
    pull_policy: always
    environment:
      - PROTON_USER=proton
      - PROTON_PASSWORD=hello
      - TELEMETRY_ENABLED=false
    ports:
      - 3218:3218 #http port for JDBC driver, default streaming mode
      - 8123:8123 #http port for JDBC driver, default batch mode
9 replies
```

Error

```
Application: Poco::Exception. Code: 1000, e.code() = 0, Exception: Failed to merge config with '/etc/proton-server/users.d/default-user.xml': Exception: Root element doesn't have the corresponding root element as the config file. It must be <proton>, Stack trace (when copying this message, always include the lines below):
```
